#!/usr/bin/env python3
"""
Kubeflow Credentials Setup Helper

This script helps you configure Kubeflow credentials without hardcoding them.
"""

import os
from pathlib import Path

def setup_credentials():
    """Interactive setup for Kubeflow credentials"""
    print("🔐 Kubeflow Credentials Setup")
    print("=" * 40)
    print("This will help you set up Kubeflow credentials securely.")
    print("Your credentials will be stored in environment variables, not in source code.\n")
    
    # Get current values (from env or defaults)
    current_endpoint = os.getenv('KUBEFLOW_ENDPOINT', 'http://localhost:8080')
    current_username = os.getenv('KUBEFLOW_USERNAME', 'user@example.com')
    current_password = os.getenv('KUBEFLOW_PASSWORD', '12341234')
    current_namespace = os.getenv('KUBEFLOW_USER_NAMESPACE', 'kubeflow-user-example-com')
    
    # Interactive prompts
    print(f"Current endpoint: {current_endpoint}")
    endpoint = input("Kubeflow endpoint (Enter to keep current): ").strip()
    if not endpoint:
        endpoint = current_endpoint
    
    print(f"\nCurrent username: {current_username}")
    username = input("Username (Enter to keep current): ").strip()
    if not username:
        username = current_username
    
    print(f"\nCurrent namespace: {current_namespace}")
    namespace = input("User namespace (Enter to keep current): ").strip()
    if not namespace:
        namespace = current_namespace
    
    # Password (hidden input would be better, but keeping it simple)
    password = input(f"\nPassword (Enter to keep current): ").strip()
    if not password:
        password = current_password
    
    # Create environment file
    env_content = f"""# Kubeflow Configuration
# Generated by setup_credentials.py
# Source this file: source kubeflow.env

export KUBEFLOW_ENDPOINT={endpoint}
export KUBEFLOW_USERNAME={username}
export KUBEFLOW_PASSWORD={password}
export KUBEFLOW_USER_NAMESPACE={namespace}
export KUBEFLOW_NAMESPACE=kubeflow
"""
    
    with open('kubeflow.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Credentials saved to kubeflow.env")
    print(f"📋 To use these credentials, run:")
    print(f"   source kubeflow.env")
    print(f"   python kfp_client.py")
    print(f"\n🔒 Security notes:")
    print(f"   - kubeflow.env is added to .gitignore")
    print(f"   - Never commit credentials to git")
    print(f"   - Use environment variables in production")

def test_credentials():
    """Test the current credential configuration"""
    print("\n🧪 Testing current credentials...")
    
    try:
        from kfp_client import RawKFPClient
        client = RawKFPClient()
        health = client.health_check()
        
        if health.get('apiServerReady'):
            print("✅ Credentials are working!")
            print(f"   Endpoint: {client.endpoint_url}")
            print(f"   Namespace: {client.namespace}")
            
            # Test basic operations
            pipelines = client.list_pipelines()
            experiments = client.list_experiments()
            runs = client.list_runs()
            
            print(f"   Found {len(pipelines.get('pipelines', []))} pipelines")
            print(f"   Found {len(experiments.get('experiments', []))} experiments")
            print(f"   Found {len(runs.get('runs', []))} runs")
        else:
            print("⚠️  API is not ready")
            
    except Exception as e:
        print(f"❌ Credential test failed: {e}")
        print("   Check your credentials and try again")

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == 'test':
        test_credentials()
    else:
        setup_credentials()
        
        # Ask if user wants to test
        test_now = input("\nTest credentials now? (y/N): ").lower().strip()
        if test_now == 'y':
            # Source the environment file first
            print("\n📝 Loading credentials...")
            env_file = Path('kubeflow.env')
            if env_file.exists():
                with open(env_file) as f:
                    for line in f:
                        if line.strip() and not line.startswith('#') and '=' in line:
                            key, value = line.strip().replace('export ', '').split('=', 1)
                            os.environ[key] = value
            
            test_credentials() 