# Azure Blob Storage ServiceAccount using Managed Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-pipeline-sa
  namespace: kubeflow-user-example-com
  annotations:
    azure.workload.identity/client-id: "12345678-1234-1234-1234-123456789012"
