# Google Cloud Storage (GCS) ServiceAccount using Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcs-pipeline-sa
  namespace: kubeflow-user-example-com
  annotations:
    iam.gke.io/gcp-service-account: kubeflow-pipelines@project-id.iam.gserviceaccount.com
